import fs from 'fs';
let v = fs.readFileSync('src/routes/_authenticated/vendor.tsx', 'utf8');
v = v.split('<h2 className="flex items-center gap-2 font-display text-xl font-bold"><Store className="size-5 text-accent-deep" /> My shops</h2>').join('<h2 className="font-display text-xl font-bold">My shops</h2>');
v = v.split('<h2 className="flex items-center gap-2 font-display text-xl font-bold"><Plus className="size-5 text-accent-deep" /> Add a product</h2>').join('<h2 className="font-display text-xl font-bold">Add a product</h2>');
v = v.split('><MessageCircle className="size-4" /> Chat</Link>').join('>Chat</Link>');
v = v.split('<p className="flex items-center gap-1 text-xs font-semibold text-accent-deep"><Bike className="size-3.5" /> Delivery: {g.delivery_status}</p>').join('<p className="text-xs font-semibold text-accent-deep">Delivery: {g.delivery_status}</p>');
v = v.split('<p className="flex items-center gap-1 text-xs font-semibold text-success"><CheckCircle2 className="size-3.5" /> PAID via {g.payment_method || "M-Pesa"} · ref {String(g.payment_ref).slice(0, 8)}</p>').join('<p className="text-xs font-semibold text-success">PAID via {g.payment_method || "M-Pesa"} · ref {String(g.payment_ref).slice(0, 8)}</p>');
v = v.split('<p className="flex items-center gap-1 text-xs font-semibold text-success"><CheckCircle2 className="size-3.5" /> PAID</p>').join('<p className="text-xs font-semibold text-success">PAID</p>');
v = v.split('<p className="flex items-center gap-1 text-xs font-semibold text-warning"><AlertTriangle className="size-3.5" /> Buyer claims direct payment - check your M-Pesa SMS before fulfilling</p>').join('<p className="text-xs font-semibold text-warning">Buyer claims direct payment - check your M-Pesa SMS before fulfilling</p>');
v = v.split('import { AlertTriangle, Bike, CheckCircle2, MessageCircle, Plus, Store } from "lucide-react";\n').join('');
fs.writeFileSync('src/routes/_authenticated/vendor.tsx', v);
console.log('vendor cleaned');
let orders = fs.readFileSync('src/routes/_authenticated/orders.tsx', 'utf8');
orders = orders.split('<p className="mt-1 flex items-center gap-1 text-xs font-semibold text-accent-deep"><Bike className="size-3.5" /> Delivery: {o.delivery_status}</p>').join('<p className="mt-1 text-xs font-semibold text-accent-deep">Delivery: {o.delivery_status}</p>');
orders = orders.split('import { Bike, MessageCircle, ReceiptText, Trash2 } from "lucide-react";').join('import { MessageCircle, ReceiptText, Trash2 } from "lucide-react";');
fs.writeFileSync('src/routes/_authenticated/orders.tsx', orders);
console.log('orders cleaned');
let checkout = fs.readFileSync('src/routes/checkout.tsx', 'utf8');
checkout = checkout.split('<Bike className="size-4" /> I need a Soko47 rider (+KSh 150)').join('I need a Soko47 rider (+KSh 150)');
checkout = checkout.split('import { Bike } from "lucide-react";\n').join('');
fs.writeFileSync('src/routes/checkout.tsx', checkout);
console.log('checkout cleaned');
let prof = fs.readFileSync('src/routes/_authenticated/profile.tsx', 'utf8');
prof = prof.split('<Label className="flex items-center gap-1"><Bot className="size-4" /> Auto-reply message</Label>').join('<Label>Auto-reply message</Label>');
prof = prof.split('<span className="inline-flex items-center gap-1"><Lock className="size-3.5" /> Private - only YOU can view & edit this page. Nobody else can touch your profile.</span>').join('Private - only YOU can view & edit this page. Nobody else can touch your profile.');
prof = prof.split('import { Bot, Lock, User } from "lucide-react";').join('import { User } from "lucide-react";');
fs.writeFileSync('src/routes/_authenticated/profile.tsx', prof);
console.log('profile cleaned');
let pay = fs.readFileSync('src/routes/pay.$id.tsx', 'utf8');
pay = pay.split('<Banknote className="size-4" /> I paid directly (cash / M-Pesa to trader)').join('I paid directly (cash / M-Pesa to trader)');
pay = pay.split('<Label className="flex items-center gap-1"><Smartphone className="size-4" /> M-Pesa number to receive the prompt</Label>').join('<Label>M-Pesa number to receive the prompt</Label>');
pay = pay.split('import { Banknote, Copy, ExternalLink, Phone, Smartphone } from "lucide-react";').join('import { Copy, ExternalLink, Phone } from "lucide-react";');
fs.writeFileSync('src/routes/pay.$id.tsx', pay);
console.log('pay cleaned');
let chat = fs.readFileSync('src/routes/_authenticated/chat.$vendorId.$buyerId.tsx', 'utf8');
chat = chat.split('import { Copy, Download, Lock, MessageCircle, Pencil, Send, Trash2, X } from "lucide-react";').join('import { Copy, Download, Pencil, Send, Trash2, X } from "lucide-react";');
chat = chat.split('<MessageCircle className="size-4 opacity-70" />').join('<div className="w-6" />');
chat = chat.split('<p className="flex items-center justify-center gap-1 pt-10 text-center text-sm text-muted-foreground"><Lock className="size-3.5" /> Messages are private - say habari to start.</p>').join('<p className="pt-10 text-center text-sm text-muted-foreground">Messages are private - say habari to start.</p>');
chat = chat.split('<Pencil className="size-3.5" /> Edit my profile (only you can edit it)').join('Edit my profile (only you can edit it)');
chat = chat.split('<Trash2 className="size-4" /> Clear chat').join('Clear chat');
fs.writeFileSync('src/routes/_authenticated/chat.$vendorId.$buyerId.tsx', chat);
console.log('chat cleaned');
let bar = fs.readFileSync('src/components/vendor-bar.tsx', 'utf8');
bar = bar.split('import { BarChart3, Store } from "lucide-react";\n').join('');
bar = bar.split('<Store className="size-3.5" /> Shop dashboard').join('Shop dashboard');
bar = bar.split('<BarChart3 className="size-3.5" /> Pro Studio').join('Pro Studio');
fs.writeFileSync('src/components/vendor-bar.tsx', bar);
console.log('vendor bar cleaned');
console.log('DONE - plain professional text everywhere');