/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SocialRouteImport } from './routes/social'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedProRouteImport } from './routes/_authenticated/pro'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRiderRouteImport } from './routes/_authenticated/rider'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsCountyRouteImport } from './routes/markets.$county'
import { Route as PayIdRouteImport } from './routes/pay.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as AuthenticatedEnrichIdRouteImport } from './routes/_authenticated/enrich.$id'
import { Route as AuthenticatedReceiptIdRouteImport } from './routes/_authenticated/receipt.$id'
import { Route as AuthenticatedChatVendorIdBuyerIdRouteImport } from './routes/_authenticated/chat.$vendorId.$buyerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProRoute = AuthenticatedProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiderRoute = AuthenticatedRiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsCountyRoute = MarketsCountyRouteImport.update({
  id: '/markets/$county',
  path: '/markets/$county',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEnrichIdRoute = AuthenticatedEnrichIdRouteImport.update({
  id: '/enrich/$id',
  path: '/enrich/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiptIdRoute = AuthenticatedReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatVendorIdBuyerIdRoute =
  AuthenticatedChatVendorIdBuyerIdRouteImport.update({
    id: '/chat/$vendorId/$buyerId',
    path: '/chat/$vendorId/$buyerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pos': typeof AuthenticatedPosRoute
  '/pro': typeof AuthenticatedProRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rider': typeof AuthenticatedRiderRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/markets/$county': typeof MarketsCountyRoute
  '/pay/$id': typeof PayIdRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/markets/': typeof MarketsIndexRoute
  '/enrich/$id': typeof AuthenticatedEnrichIdRoute
  '/receipt/$id': typeof AuthenticatedReceiptIdRoute
  '/chat/$vendorId/$buyerId': typeof AuthenticatedChatVendorIdBuyerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pos': typeof AuthenticatedPosRoute
  '/pro': typeof AuthenticatedProRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rider': typeof AuthenticatedRiderRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/markets/$county': typeof MarketsCountyRoute
  '/pay/$id': typeof PayIdRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/markets': typeof MarketsIndexRoute
  '/enrich/$id': typeof AuthenticatedEnrichIdRoute
  '/receipt/$id': typeof AuthenticatedReceiptIdRoute
  '/chat/$vendorId/$buyerId': typeof AuthenticatedChatVendorIdBuyerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/pro': typeof AuthenticatedProRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rider': typeof AuthenticatedRiderRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/vendor': typeof AuthenticatedVendorRoute
  '/markets/$county': typeof MarketsCountyRoute
  '/pay/$id': typeof PayIdRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/markets/': typeof MarketsIndexRoute
  '/_authenticated/enrich/$id': typeof AuthenticatedEnrichIdRoute
  '/_authenticated/receipt/$id': typeof AuthenticatedReceiptIdRoute
  '/_authenticated/chat/$vendorId/$buyerId': typeof AuthenticatedChatVendorIdBuyerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/privacy'
    | '/sell'
    | '/social'
    | '/terms'
    | '/account'
    | '/admin'
    | '/chats'
    | '/help'
    | '/orders'
    | '/pos'
    | '/pro'
    | '/profile'
    | '/rider'
    | '/settings'
    | '/vendor'
    | '/markets/$county'
    | '/pay/$id'
    | '/product/$id'
    | '/shop/$slug'
    | '/markets/'
    | '/enrich/$id'
    | '/receipt/$id'
    | '/chat/$vendorId/$buyerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/privacy'
    | '/sell'
    | '/social'
    | '/terms'
    | '/account'
    | '/admin'
    | '/chats'
    | '/help'
    | '/orders'
    | '/pos'
    | '/pro'
    | '/profile'
    | '/rider'
    | '/settings'
    | '/vendor'
    | '/markets/$county'
    | '/pay/$id'
    | '/product/$id'
    | '/shop/$slug'
    | '/markets'
    | '/enrich/$id'
    | '/receipt/$id'
    | '/chat/$vendorId/$buyerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/privacy'
    | '/sell'
    | '/social'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/chats'
    | '/_authenticated/help'
    | '/_authenticated/orders'
    | '/_authenticated/pos'
    | '/_authenticated/pro'
    | '/_authenticated/profile'
    | '/_authenticated/rider'
    | '/_authenticated/settings'
    | '/_authenticated/vendor'
    | '/markets/$county'
    | '/pay/$id'
    | '/product/$id'
    | '/shop/$slug'
    | '/markets/'
    | '/_authenticated/enrich/$id'
    | '/_authenticated/receipt/$id'
    | '/_authenticated/chat/$vendorId/$buyerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  PrivacyRoute: typeof PrivacyRoute
  SellRoute: typeof SellRoute
  SocialRoute: typeof SocialRoute
  TermsRoute: typeof TermsRoute
  MarketsCountyRoute: typeof MarketsCountyRoute
  PayIdRoute: typeof PayIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ShopSlugRoute: typeof ShopSlugRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro': {
      id: '/_authenticated/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AuthenticatedProRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rider': {
      id: '/_authenticated/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof AuthenticatedRiderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$county': {
      id: '/markets/$county'
      path: '/markets/$county'
      fullPath: '/markets/$county'
      preLoaderRoute: typeof MarketsCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/enrich/$id': {
      id: '/_authenticated/enrich/$id'
      path: '/enrich/$id'
      fullPath: '/enrich/$id'
      preLoaderRoute: typeof AuthenticatedEnrichIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipt/$id': {
      id: '/_authenticated/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof AuthenticatedReceiptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$vendorId/$buyerId': {
      id: '/_authenticated/chat/$vendorId/$buyerId'
      path: '/chat/$vendorId/$buyerId'
      fullPath: '/chat/$vendorId/$buyerId'
      preLoaderRoute: typeof AuthenticatedChatVendorIdBuyerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProRoute: typeof AuthenticatedProRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRiderRoute: typeof AuthenticatedRiderRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRoute
  AuthenticatedEnrichIdRoute: typeof AuthenticatedEnrichIdRoute
  AuthenticatedReceiptIdRoute: typeof AuthenticatedReceiptIdRoute
  AuthenticatedChatVendorIdBuyerIdRoute: typeof AuthenticatedChatVendorIdBuyerIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProRoute: AuthenticatedProRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRiderRoute: AuthenticatedRiderRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVendorRoute: AuthenticatedVendorRoute,
  AuthenticatedEnrichIdRoute: AuthenticatedEnrichIdRoute,
  AuthenticatedReceiptIdRoute: AuthenticatedReceiptIdRoute,
  AuthenticatedChatVendorIdBuyerIdRoute: AuthenticatedChatVendorIdBuyerIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  PrivacyRoute: PrivacyRoute,
  SellRoute: SellRoute,
  SocialRoute: SocialRoute,
  TermsRoute: TermsRoute,
  MarketsCountyRoute: MarketsCountyRoute,
  PayIdRoute: PayIdRoute,
  ProductIdRoute: ProductIdRoute,
  ShopSlugRoute: ShopSlugRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
